tags:
- name: users
  description: users API
- name: questions
  description: questions API

paths:
# [GET] users
  /users:
    get:
      tags:
      - users
      summary: Find All Users
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] users
    post:
      tags:
      - users
      summary: Add User
      parameters:
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/users'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] users/id
  /users/{id}:
    get:
      tags:
      - users
      summary: Find User By Id
      parameters:
      - name: id
        in: path
        description: User Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] users/id
    put:
      tags:
      - users
      summary: Update User By Id
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
        type: integer
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/users'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] users/id
    delete:
      tags:
      - users
      summary: Delete User By Id
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] questions
  /questions:
    get:
      tags:
      - questions
      summary: Find All Questions
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'  

  # [POST] questions
    post:
      tags:
      - questions
      summary: Add Questions
      parameters:
      - name: body
        in: body
        description: questions Data
        required: true
        schema:
          $ref: '#/definitions/questions'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] questions/id
  /questions/{id}:
    get:
      tags:
      - users
      summary: Find Questions By Id
      parameters:
      - name: id
        in: path
        description: User Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] questions/id
    put:
      tags:
      - questions
      summary: Update Question By Id
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
        type: integer
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/questions'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] questions/id
    delete:
      tags:
      - questions
      summary: Delete Question By Id
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'  
            

# definitions
definitions:
  users:
    type: object
    required:
        - email
        - password
        - username
    properties:
      id:
        type: integer
        description: user Id
      email:
        type: string
        description: user Email
      username:
        type: string
        description: user Username
      password:
        type: string
        description: user Password
      firstName:
        type: string
        description: user First name 
      lastName:
        type: string
        description: user Last name
  questions:
    type: object
    required:
        - question
        - userId
    properties:
      id:
        type: integer
        description: question Id
      question:
        type: string
        description: question Question
      upVote:
        type: integer
        description: user upVote
      downVote:
        type: integer
        description: user downVote
      userId:
        type: string
        description: user userID 

schemes:
 - https
 - http





